module.exports = {
  // flagCountry: [
  //   {
  //     code: 'IQ',
  //     dial_code: '+964',
  //     flag: require('../../assets/images/flags/iq.png'),
  //     name: 'Iraq',
  //   },
  //   {
  //     code: 'AF',
  //     dial_code: '+93',
  //     flag: require('../../assets/images/flags/af.png'),
  //     name: 'Afghanistan',
  //   },
  //   {
  //     code: 'AX',
  //     dial_code: '+358',
  //     flag: require('../../assets/images/flags/ax.png'),
  //     name: 'Aland Islands',
  //   },
  //   {
  //     code: 'AL',
  //     dial_code: '+355',
  //     flag: require('../../assets/images/flags/al.png'),
  //     name: 'Albania',
  //   },
  //   {
  //     code: 'DZ',
  //     dial_code: '+213',
  //     flag: require('../../assets/images/flags/dz.png'),
  //     name: 'Algeria',
  //   },
  //   {
  //     code: 'AS',
  //     dial_code: '+1684',
  //     flag: require('../../assets/images/flags/as.png'),
  //     name: 'AmericanSamoa',
  //   },
  //   {
  //     code: 'AD',
  //     dial_code: '+376',
  //     flag: require('../../assets/images/flags/ad.png'),
  //     name: 'Andorra',
  //   },
  //   {
  //     code: 'AO',
  //     dial_code: '+244',
  //     flag: require('../../assets/images/flags/ao.png'),
  //     name: 'Angola',
  //   },
  //   {
  //     code: 'AI',
  //     dial_code: '+1264',
  //     flag: require('../../assets/images/flags/ai.png'),
  //     name: 'Anguilla',
  //   },
  //   {
  //     code: 'AQ',
  //     dial_code: '+672',
  //     flag: require('../../assets/images/flags/aq.png'),
  //     name: 'Antarctica',
  //   },
  //   {
  //     code: 'AG',
  //     dial_code: '+1268',
  //     flag: require('../../assets/images/flags/ag.png'),
  //     name: 'Antigua and Barbuda',
  //   },
  //   {
  //     code: 'AR',
  //     dial_code: '+54',
  //     flag: require('../../assets/images/flags/ar.png'),
  //     name: 'Argentina',
  //   },
  //   {
  //     code: 'AM',
  //     dial_code: '+374',
  //     flag: require('../../assets/images/flags/am.png'),
  //     name: 'Armenia',
  //   },
  //   {
  //     code: 'AW',
  //     dial_code: '+297',
  //     flag: require('../../assets/images/flags/aw.png'),
  //     name: 'Aruba',
  //   },
  //   {
  //     code: 'AU',
  //     dial_code: '+61',
  //     flag: require('../../assets/images/flags/au.png'),
  //     name: 'Australia',
  //   },
  //   {
  //     code: 'AT',
  //     dial_code: '+43',
  //     flag: require('../../assets/images/flags/at.png'),
  //     name: 'Austria',
  //   },
  //   {
  //     code: 'AZ',
  //     dial_code: '+994',
  //     flag: require('../../assets/images/flags/az.png'),
  //     name: 'Azerbaijan',
  //   },
  //   {
  //     code: 'BS',
  //     dial_code: '+1242',
  //     flag: require('../../assets/images/flags/bs.png'),
  //     name: 'Bahamas',
  //   },
  //   {
  //     code: 'BH',
  //     dial_code: '+973',
  //     flag: require('../../assets/images/flags/bh.png'),
  //     name: 'Bahrain',
  //   },
  //   {
  //     code: 'BD',
  //     dial_code: '+880',
  //     flag: require('../../assets/images/flags/bd.png'),
  //     name: 'Bangladesh',
  //   },
  //   {
  //     code: 'BB',
  //     dial_code: '+1246',
  //     flag: require('../../assets/images/flags/bb.png'),
  //     name: 'Barbados',
  //   },
  //   {
  //     code: 'BY',
  //     dial_code: '+375',
  //     flag: require('../../assets/images/flags/by.png'),
  //     name: 'Belarus',
  //   },
  //   {
  //     code: 'BE',
  //     dial_code: '+32',
  //     flag: require('../../assets/images/flags/be.png'),
  //     name: 'Belgium',
  //   },
  //   {
  //     code: 'BZ',
  //     dial_code: '+501',
  //     flag: require('../../assets/images/flags/bz.png'),
  //     name: 'Belize',
  //   },
  //   {
  //     code: 'BJ',
  //     dial_code: '+229',
  //     flag: require('../../assets/images/flags/bj.png'),
  //     name: 'Benin',
  //   },
  //   {
  //     code: 'BM',
  //     dial_code: '+1441',
  //     flag: require('../../assets/images/flags/bm.png'),
  //     name: 'Bermuda',
  //   },
  //   {
  //     code: 'BT',
  //     dial_code: '+975',
  //     flag: require('../../assets/images/flags/bt.png'),
  //     name: 'Bhutan',
  //   },
  //   {
  //     code: 'BO',
  //     dial_code: '+591',
  //     flag: require('../../assets/images/flags/bo.png'),
  //     name: 'Bolivia, Plurinational State of',
  //   },
  //   {
  //     code: 'BA',
  //     dial_code: '+387',
  //     flag: require('../../assets/images/flags/ba.png'),
  //     name: 'Bosnia and Herzegovina',
  //   },
  //   {
  //     code: 'BW',
  //     dial_code: '+267',
  //     flag: require('../../assets/images/flags/bw.png'),
  //     name: 'Botswana',
  //   },
  //   {
  //     code: 'BR',
  //     dial_code: '+55',
  //     flag: require('../../assets/images/flags/br.png'),
  //     name: 'Brazil',
  //   },
  //   {
  //     code: 'IO',
  //     dial_code: '+246',
  //     flag: require('../../assets/images/flags/io.png'),
  //     name: 'British Indian Ocean Territory',
  //   },
  //   {
  //     code: 'BN',
  //     dial_code: '+673',
  //     flag: require('../../assets/images/flags/bn.png'),
  //     name: 'Brunei Darussalam',
  //   },
  //   {
  //     code: 'BG',
  //     dial_code: '+359',
  //     flag: require('../../assets/images/flags/bg.png'),
  //     name: 'Bulgaria',
  //   },
  //   {
  //     code: 'BF',
  //     dial_code: '+226',
  //     flag: require('../../assets/images/flags/bf.png'),
  //     name: 'Burkina Faso',
  //   },
  //   {
  //     code: 'BI',
  //     dial_code: '+257',
  //     flag: require('../../assets/images/flags/bi.png'),
  //     name: 'Burundi',
  //   },
  //   {
  //     code: 'KH',
  //     dial_code: '+855',
  //     flag: require('../../assets/images/flags/kh.png'),
  //     name: 'Cambodia',
  //   },
  //   {
  //     code: 'CM',
  //     dial_code: '+237',
  //     flag: require('../../assets/images/flags/cm.png'),
  //     name: 'Cameroon',
  //   },
  //   {
  //     code: 'CA',
  //     dial_code: '+1',
  //     flag: require('../../assets/images/flags/ca.png'),
  //     name: 'Canada',
  //   },
  //   {
  //     code: 'CV',
  //     dial_code: '+238',
  //     flag: require('../../assets/images/flags/cv.png'),
  //     name: 'Cape Verde',
  //   },
  //   {
  //     code: 'KY',
  //     dial_code: '+ 345',
  //     flag: require('../../assets/images/flags/ky.png'),
  //     name: 'Cayman Islands',
  //   },
  //   {
  //     code: 'CF',
  //     dial_code: '+236',
  //     flag: require('../../assets/images/flags/cf.png'),
  //     name: 'Central African Republic',
  //   },
  //   {
  //     code: 'TD',
  //     dial_code: '+235',
  //     flag: require('../../assets/images/flags/td.png'),
  //     name: 'Chad',
  //   },
  //   {
  //     code: 'CL',
  //     dial_code: '+56',
  //     flag: require('../../assets/images/flags/cl.png'),
  //     name: 'Chile',
  //   },
  //   {
  //     code: 'CN',
  //     dial_code: '+86',
  //     flag: require('../../assets/images/flags/cn.png'),
  //     name: 'China',
  //   },
  //   {
  //     code: 'CX',
  //     dial_code: '+61',
  //     flag: require('../../assets/images/flags/cx.png'),
  //     name: 'Christmas Island',
  //   },
  //   {
  //     code: 'CC',
  //     dial_code: '+61',
  //     flag: require('../../assets/images/flags/cc.png'),
  //     name: 'Cocos (Keeling) Islands',
  //   },
  //   {
  //     code: 'CO',
  //     dial_code: '+57',
  //     flag: require('../../assets/images/flags/co.png'),
  //     name: 'Colombia',
  //   },
  //   {
  //     code: 'KM',
  //     dial_code: '+269',
  //     flag: require('../../assets/images/flags/km.png'),
  //     name: 'Comoros',
  //   },
  //   {
  //     code: 'CG',
  //     dial_code: '+242',
  //     flag: require('../../assets/images/flags/cg.png'),
  //     name: 'Congo',
  //   },
  //   {
  //     code: 'CD',
  //     dial_code: '+243',
  //     flag: require('../../assets/images/flags/cd.png'),
  //     name: 'Congo, The Democratic Republic of the Congo',
  //   },
  //   {
  //     code: 'CK',
  //     dial_code: '+682',
  //     flag: require('../../assets/images/flags/ck.png'),
  //     name: 'Cook Islands',
  //   },
  //   {
  //     code: 'CR',
  //     dial_code: '+506',
  //     flag: require('../../assets/images/flags/cr.png'),
  //     name: 'Costa Rica',
  //   },
  //   {
  //     code: 'CI',
  //     dial_code: '+225',
  //     flag: require('../../assets/images/flags/ci.png'),
  //     name: "Cote d'Ivoire",
  //   },
  //   {
  //     code: 'HR',
  //     dial_code: '+385',
  //     flag: require('../../assets/images/flags/hr.png'),
  //     name: 'Croatia',
  //   },
  //   {
  //     code: 'CU',
  //     dial_code: '+53',
  //     flag: require('../../assets/images/flags/cu.png'),
  //     name: 'Cuba',
  //   },
  //   {
  //     code: 'CY',
  //     dial_code: '+357',
  //     flag: require('../../assets/images/flags/cy.png'),
  //     name: 'Cyprus',
  //   },
  //   {
  //     code: 'CZ',
  //     dial_code: '+420',
  //     flag: require('../../assets/images/flags/cz.png'),
  //     name: 'Czech Republic',
  //   },
  //   {
  //     code: 'DK',
  //     dial_code: '+45',
  //     flag: require('../../assets/images/flags/dk.png'),
  //     name: 'Denmark',
  //   },
  //   {
  //     code: 'DJ',
  //     dial_code: '+253',
  //     flag: require('../../assets/images/flags/dj.png'),
  //     name: 'Djibouti',
  //   },
  //   {
  //     code: 'DM',
  //     dial_code: '+1767',
  //     flag: require('../../assets/images/flags/dm.png'),
  //     name: 'Dominica',
  //   },
  //   {
  //     code: 'DO',
  //     dial_code: '+1849',
  //     flag: require('../../assets/images/flags/do.png'),
  //     name: 'Dominican Republic',
  //   },
  //   {
  //     code: 'EC',
  //     dial_code: '+593',
  //     flag: require('../../assets/images/flags/ec.png'),
  //     name: 'Ecuador',
  //   },
  //   {
  //     code: 'EG',
  //     dial_code: '+20',
  //     flag: require('../../assets/images/flags/eg.png'),
  //     name: 'Egypt',
  //   },
  //   {
  //     code: 'SV',
  //     dial_code: '+503',
  //     flag: require('../../assets/images/flags/sv.png'),
  //     name: 'El Salvador',
  //   },
  //   {
  //     code: 'GQ',
  //     dial_code: '+240',
  //     flag: require('../../assets/images/flags/gq.png'),
  //     name: 'Equatorial Guinea',
  //   },
  //   {
  //     code: 'ER',
  //     dial_code: '+291',
  //     flag: require('../../assets/images/flags/er.png'),
  //     name: 'Eritrea',
  //   },
  //   {
  //     code: 'EE',
  //     dial_code: '+372',
  //     flag: require('../../assets/images/flags/ee.png'),
  //     name: 'Estonia',
  //   },
  //   {
  //     code: 'ET',
  //     dial_code: '+251',
  //     flag: require('../../assets/images/flags/et.png'),
  //     name: 'Ethiopia',
  //   },
  //   {
  //     code: 'FK',
  //     dial_code: '+500',
  //     flag: require('../../assets/images/flags/fk.png'),
  //     name: 'Falkland Islands (Malvinas)',
  //   },
  //   {
  //     code: 'FO',
  //     dial_code: '+298',
  //     flag: require('../../assets/images/flags/fo.png'),
  //     name: 'Faroe Islands',
  //   },
  //   {
  //     code: 'FJ',
  //     dial_code: '+679',
  //     flag: require('../../assets/images/flags/fj.png'),
  //     name: 'Fiji',
  //   },
  //   {
  //     code: 'FI',
  //     dial_code: '+358',
  //     flag: require('../../assets/images/flags/fi.png'),
  //     name: 'Finland',
  //   },
  //   {
  //     code: 'FR',
  //     dial_code: '+33',
  //     flag: require('../../assets/images/flags/fr.png'),
  //     name: 'France',
  //   },
  //   {
  //     code: 'GF',
  //     dial_code: '+594',
  //     flag: require('../../assets/images/flags/gf.png'),
  //     name: 'French Guiana',
  //   },
  //   {
  //     code: 'PF',
  //     dial_code: '+689',
  //     flag: require('../../assets/images/flags/pf.png'),
  //     name: 'French Polynesia',
  //   },
  //   {
  //     code: 'GA',
  //     dial_code: '+241',
  //     flag: require('../../assets/images/flags/ga.png'),
  //     name: 'Gabon',
  //   },
  //   {
  //     code: 'GM',
  //     dial_code: '+220',
  //     flag: require('../../assets/images/flags/gm.png'),
  //     name: 'Gambia',
  //   },
  //   {
  //     code: 'GE',
  //     dial_code: '+995',
  //     flag: require('../../assets/images/flags/ge.png'),
  //     name: 'Georgia',
  //   },
  //   {
  //     code: 'DE',
  //     dial_code: '+49',
  //     flag: require('../../assets/images/flags/de.png'),
  //     name: 'Germany',
  //   },
  //   {
  //     code: 'GH',
  //     dial_code: '+233',
  //     flag: require('../../assets/images/flags/gh.png'),
  //     name: 'Ghana',
  //   },
  //   {
  //     code: 'GI',
  //     dial_code: '+350',
  //     flag: require('../../assets/images/flags/gi.png'),
  //     name: 'Gibraltar',
  //   },
  //   {
  //     code: 'GR',
  //     dial_code: '+30',
  //     flag: require('../../assets/images/flags/gr.png'),
  //     name: 'Greece',
  //   },
  //   {
  //     code: 'GL',
  //     dial_code: '+299',
  //     flag: require('../../assets/images/flags/gl.png'),
  //     name: 'Greenland',
  //   },
  //   {
  //     code: 'GD',
  //     dial_code: '+1473',
  //     flag: require('../../assets/images/flags/gd.png'),
  //     name: 'Grenada',
  //   },
  //   {
  //     code: 'GP',
  //     dial_code: '+590',
  //     flag: require('../../assets/images/flags/gp.png'),
  //     name: 'Guadeloupe',
  //   },
  //   {
  //     code: 'GU',
  //     dial_code: '+1671',
  //     flag: require('../../assets/images/flags/gu.png'),
  //     name: 'Guam',
  //   },
  //   {
  //     code: 'GT',
  //     dial_code: '+502',
  //     flag: require('../../assets/images/flags/gt.png'),
  //     name: 'Guatemala',
  //   },
  //   {
  //     code: 'GG',
  //     dial_code: '+44',
  //     flag: require('../../assets/images/flags/gg.png'),
  //     name: 'Guernsey',
  //   },
  //   {
  //     code: 'GN',
  //     dial_code: '+224',
  //     flag: require('../../assets/images/flags/gn.png'),
  //     name: 'Guinea',
  //   },
  //   {
  //     code: 'GW',
  //     dial_code: '+245',
  //     flag: require('../../assets/images/flags/gw.png'),
  //     name: 'Guinea-Bissau',
  //   },
  //   {
  //     code: 'GY',
  //     dial_code: '+595',
  //     flag: require('../../assets/images/flags/gy.png'),
  //     name: 'Guyana',
  //   },
  //   {
  //     code: 'HT',
  //     dial_code: '+509',
  //     flag: require('../../assets/images/flags/ht.png'),
  //     name: 'Haiti',
  //   },
  //   {
  //     code: 'VA',
  //     dial_code: '+379',
  //     flag: require('../../assets/images/flags/va.png'),
  //     name: 'Holy See (Vatican City State)',
  //   },
  //   {
  //     code: 'HN',
  //     dial_code: '+504',
  //     flag: require('../../assets/images/flags/hn.png'),
  //     name: 'Honduras',
  //   },
  //   {
  //     code: 'HK',
  //     dial_code: '+852',
  //     flag: require('../../assets/images/flags/hk.png'),
  //     name: 'Hong Kong',
  //   },
  //   {
  //     code: 'HU',
  //     dial_code: '+36',
  //     flag: require('../../assets/images/flags/hu.png'),
  //     name: 'Hungary',
  //   },
  //   {
  //     code: 'IS',
  //     dial_code: '+354',
  //     flag: require('../../assets/images/flags/is.png'),
  //     name: 'Iceland',
  //   },
  //   {
  //     code: 'IN',
  //     dial_code: '+91',
  //     flag: require('../../assets/images/flags/in.png'),
  //     name: 'India',
  //   },
  //   {
  //     code: 'ID',
  //     dial_code: '+62',
  //     flag: require('../../assets/images/flags/id.png'),
  //     name: 'Indonesia',
  //   },
  //   {
  //     code: 'IR',
  //     dial_code: '+98',
  //     flag: require('../../assets/images/flags/ir.png'),
  //     name: 'Iran, Islamic Republic of Persian Gulf',
  //   },
  //   {
  //     code: 'IE',
  //     dial_code: '+353',
  //     flag: require('../../assets/images/flags/ie.png'),
  //     name: 'Ireland',
  //   },
  //   {
  //     code: 'IM',
  //     dial_code: '+44',
  //     flag: require('../../assets/images/flags/im.png'),
  //     name: 'Isle of Man',
  //   },
  //   {
  //     code: 'IL',
  //     dial_code: '+972',
  //     flag: require('../../assets/images/flags/il.png'),
  //     name: 'Israel',
  //   },
  //   {
  //     code: 'IT',
  //     dial_code: '+39',
  //     flag: require('../../assets/images/flags/it.png'),
  //     name: 'Italy',
  //   },
  //   {
  //     code: 'JM',
  //     dial_code: '+1876',
  //     flag: require('../../assets/images/flags/jm.png'),
  //     name: 'Jamaica',
  //   },
  //   {
  //     code: 'JP',
  //     dial_code: '+81',
  //     flag: require('../../assets/images/flags/jp.png'),
  //     name: 'Japan',
  //   },
  //   {
  //     code: 'JE',
  //     dial_code: '+44',
  //     flag: require('../../assets/images/flags/je.png'),
  //     name: 'Jersey',
  //   },
  //   {
  //     code: 'JO',
  //     dial_code: '+962',
  //     flag: require('../../assets/images/flags/jo.png'),
  //     name: 'Jordan',
  //   },
  //   {
  //     code: 'KZ',
  //     dial_code: '+77',
  //     flag: require('../../assets/images/flags/kz.png'),
  //     name: 'Kazakhstan',
  //   },
  //   {
  //     code: 'KE',
  //     dial_code: '+254',
  //     flag: require('../../assets/images/flags/ke.png'),
  //     name: 'Kenya',
  //   },
  //   {
  //     code: 'KI',
  //     dial_code: '+686',
  //     flag: require('../../assets/images/flags/ki.png'),
  //     name: 'Kiribati',
  //   },
  //   {
  //     code: 'KP',
  //     dial_code: '+850',
  //     flag: require('../../assets/images/flags/kp.png'),
  //     name: "Korea, Democratic People's Republic of Korea",
  //   },
  //   {
  //     code: 'KR',
  //     dial_code: '+82',
  //     flag: require('../../assets/images/flags/kr.png'),
  //     name: 'Korea, Republic of South Korea',
  //   },
  //   {
  //     code: 'KW',
  //     dial_code: '+965',
  //     flag: require('../../assets/images/flags/kw.png'),
  //     name: 'Kuwait',
  //   },
  //   {
  //     code: 'KG',
  //     dial_code: '+996',
  //     flag: require('../../assets/images/flags/kg.png'),
  //     name: 'Kyrgyzstan',
  //   },
  //   {
  //     code: 'LA',
  //     dial_code: '+856',
  //     flag: require('../../assets/images/flags/la.png'),
  //     name: 'Laos',
  //   },
  //   {
  //     code: 'LV',
  //     dial_code: '+371',
  //     flag: require('../../assets/images/flags/lv.png'),
  //     name: 'Latvia',
  //   },
  //   {
  //     code: 'LB',
  //     dial_code: '+961',
  //     flag: require('../../assets/images/flags/lb.png'),
  //     name: 'Lebanon',
  //   },
  //   {
  //     code: 'LS',
  //     dial_code: '+266',
  //     flag: require('../../assets/images/flags/ls.png'),
  //     name: 'Lesotho',
  //   },
  //   {
  //     code: 'LR',
  //     dial_code: '+231',
  //     flag: require('../../assets/images/flags/lr.png'),
  //     name: 'Liberia',
  //   },
  //   {
  //     code: 'LY',
  //     dial_code: '+218',
  //     flag: require('../../assets/images/flags/ly.png'),
  //     name: 'Libyan Arab Jamahiriya',
  //   },
  //   {
  //     code: 'LI',
  //     dial_code: '+423',
  //     flag: require('../../assets/images/flags/li.png'),
  //     name: 'Liechtenstein',
  //   },
  //   {
  //     code: 'LT',
  //     dial_code: '+370',
  //     flag: require('../../assets/images/flags/lt.png'),
  //     name: 'Lithuania',
  //   },
  //   {
  //     code: 'LU',
  //     dial_code: '+352',
  //     flag: require('../../assets/images/flags/lu.png'),
  //     name: 'Luxembourg',
  //   },
  //   {
  //     code: 'MO',
  //     dial_code: '+853',
  //     flag: require('../../assets/images/flags/mo.png'),
  //     name: 'Macao',
  //   },
  //   {
  //     code: 'MK',
  //     dial_code: '+389',
  //     flag: require('../../assets/images/flags/mk.png'),
  //     name: 'Macedonia',
  //   },
  //   {
  //     code: 'MG',
  //     dial_code: '+261',
  //     flag: require('../../assets/images/flags/mg.png'),
  //     name: 'Madagascar',
  //   },
  //   {
  //     code: 'MW',
  //     dial_code: '+265',
  //     flag: require('../../assets/images/flags/mw.png'),
  //     name: 'Malawi',
  //   },
  //   {
  //     code: 'MY',
  //     dial_code: '+60',
  //     flag: require('../../assets/images/flags/my.png'),
  //     name: 'Malaysia',
  //   },
  //   {
  //     code: 'MV',
  //     dial_code: '+960',
  //     flag: require('../../assets/images/flags/mv.png'),
  //     name: 'Maldives',
  //   },
  //   {
  //     code: 'ML',
  //     dial_code: '+223',
  //     flag: require('../../assets/images/flags/ml.png'),
  //     name: 'Mali',
  //   },
  //   {
  //     code: 'MT',
  //     dial_code: '+356',
  //     flag: require('../../assets/images/flags/mt.png'),
  //     name: 'Malta',
  //   },
  //   {
  //     code: 'MH',
  //     dial_code: '+692',
  //     flag: require('../../assets/images/flags/mh.png'),
  //     name: 'Marshall Islands',
  //   },
  //   {
  //     code: 'MQ',
  //     dial_code: '+596',
  //     flag: require('../../assets/images/flags/mq.png'),
  //     name: 'Martinique',
  //   },
  //   {
  //     code: 'MR',
  //     dial_code: '+222',
  //     flag: require('../../assets/images/flags/mr.png'),
  //     name: 'Mauritania',
  //   },
  //   {
  //     code: 'MU',
  //     dial_code: '+230',
  //     flag: require('../../assets/images/flags/mu.png'),
  //     name: 'Mauritius',
  //   },
  //   {
  //     code: 'YT',
  //     dial_code: '+262',
  //     flag: require('../../assets/images/flags/yt.png'),
  //     name: 'Mayotte',
  //   },
  //   {
  //     code: 'MX',
  //     dial_code: '+52',
  //     flag: require('../../assets/images/flags/mx.png'),
  //     name: 'Mexico',
  //   },
  //   {
  //     code: 'FM',
  //     dial_code: '+691',
  //     flag: require('../../assets/images/flags/fm.png'),
  //     name: 'Micronesia, Federated States of Micronesia',
  //   },
  //   {
  //     code: 'MD',
  //     dial_code: '+373',
  //     flag: require('../../assets/images/flags/md.png'),
  //     name: 'Moldova',
  //   },
  //   {
  //     code: 'MC',
  //     dial_code: '+377',
  //     flag: require('../../assets/images/flags/mc.png'),
  //     name: 'Monaco',
  //   },
  //   {
  //     code: 'MN',
  //     dial_code: '+976',
  //     flag: require('../../assets/images/flags/mn.png'),
  //     name: 'Mongolia',
  //   },
  //   {
  //     code: 'ME',
  //     dial_code: '+382',
  //     flag: require('../../assets/images/flags/me.png'),
  //     name: 'Montenegro',
  //   },
  //   {
  //     code: 'MS',
  //     dial_code: '+1664',
  //     flag: require('../../assets/images/flags/ms.png'),
  //     name: 'Montserrat',
  //   },
  //   {
  //     code: 'MA',
  //     dial_code: '+212',
  //     flag: require('../../assets/images/flags/ma.png'),
  //     name: 'Morocco',
  //   },
  //   {
  //     code: 'MZ',
  //     dial_code: '+258',
  //     flag: require('../../assets/images/flags/mz.png'),
  //     name: 'Mozambique',
  //   },
  //   {
  //     code: 'MM',
  //     dial_code: '+95',
  //     flag: require('../../assets/images/flags/mm.png'),
  //     name: 'Myanmar',
  //   },
  //   {
  //     code: 'NA',
  //     dial_code: '+264',
  //     flag: require('../../assets/images/flags/na.png'),
  //     name: 'Namibia',
  //   },
  //   {
  //     code: 'NR',
  //     dial_code: '+674',
  //     flag: require('../../assets/images/flags/nr.png'),
  //     name: 'Nauru',
  //   },
  //   {
  //     code: 'NP',
  //     dial_code: '+977',
  //     flag: require('../../assets/images/flags/np.png'),
  //     name: 'Nepal',
  //   },
  //   {
  //     code: 'NL',
  //     dial_code: '+31',
  //     flag: require('../../assets/images/flags/nl.png'),
  //     name: 'Netherlands',
  //   },
  //   {
  //     code: 'AN',
  //     dial_code: '+599',
  //     flag: require('../../assets/images/flags/an.png'),
  //     name: 'Netherlands Antilles',
  //   },
  //   {
  //     code: 'NC',
  //     dial_code: '+687',
  //     flag: require('../../assets/images/flags/nc.png'),
  //     name: 'New Caledonia',
  //   },
  //   {
  //     code: 'NZ',
  //     dial_code: '+64',
  //     flag: require('../../assets/images/flags/nz.png'),
  //     name: 'New Zealand',
  //   },
  //   {
  //     code: 'NI',
  //     dial_code: '+505',
  //     flag: require('../../assets/images/flags/ni.png'),
  //     name: 'Nicaragua',
  //   },
  //   {
  //     code: 'NE',
  //     dial_code: '+227',
  //     flag: require('../../assets/images/flags/ne.png'),
  //     name: 'Niger',
  //   },
  //   {
  //     code: 'NG',
  //     dial_code: '+234',
  //     flag: require('../../assets/images/flags/ng.png'),
  //     name: 'Nigeria',
  //   },
  //   {
  //     code: 'NU',
  //     dial_code: '+683',
  //     flag: require('../../assets/images/flags/nu.png'),
  //     name: 'Niue',
  //   },
  //   {
  //     code: 'NF',
  //     dial_code: '+672',
  //     flag: require('../../assets/images/flags/nf.png'),
  //     name: 'Norfolk Island',
  //   },
  //   {
  //     code: 'MP',
  //     dial_code: '+1670',
  //     flag: require('../../assets/images/flags/mp.png'),
  //     name: 'Northern Mariana Islands',
  //   },
  //   {
  //     code: 'NO',
  //     dial_code: '+47',
  //     flag: require('../../assets/images/flags/no.png'),
  //     name: 'Norway',
  //   },
  //   {
  //     code: 'OM',
  //     dial_code: '+968',
  //     flag: require('../../assets/images/flags/om.png'),
  //     name: 'Oman',
  //   },
  //   {
  //     code: 'PK',
  //     dial_code: '+92',
  //     flag: require('../../assets/images/flags/pk.png'),
  //     name: 'Pakistan',
  //   },
  //   {
  //     code: 'PW',
  //     dial_code: '+680',
  //     flag: require('../../assets/images/flags/pw.png'),
  //     name: 'Palau',
  //   },
  //   {
  //     code: 'PS',
  //     dial_code: '+970',
  //     flag: require('../../assets/images/flags/ps.png'),
  //     name: 'Palestinian Territory, Occupied',
  //   },
  //   {
  //     code: 'PA',
  //     dial_code: '+507',
  //     flag: require('../../assets/images/flags/pa.png'),
  //     name: 'Panama',
  //   },
  //   {
  //     code: 'PG',
  //     dial_code: '+675',
  //     flag: require('../../assets/images/flags/pg.png'),
  //     name: 'Papua New Guinea',
  //   },
  //   {
  //     code: 'PY',
  //     dial_code: '+595',
  //     flag: require('../../assets/images/flags/py.png'),
  //     name: 'Paraguay',
  //   },
  //   {
  //     code: 'PE',
  //     dial_code: '+51',
  //     flag: require('../../assets/images/flags/pe.png'),
  //     name: 'Peru',
  //   },
  //   {
  //     code: 'PH',
  //     dial_code: '+63',
  //     flag: require('../../assets/images/flags/ph.png'),
  //     name: 'Philippines',
  //   },
  //   {
  //     code: 'PN',
  //     dial_code: '+872',
  //     flag: require('../../assets/images/flags/pn.png'),
  //     name: 'Pitcairn',
  //   },
  //   {
  //     code: 'PL',
  //     dial_code: '+48',
  //     flag: require('../../assets/images/flags/pl.png'),
  //     name: 'Poland',
  //   },
  //   {
  //     code: 'PT',
  //     dial_code: '+351',
  //     flag: require('../../assets/images/flags/pt.png'),
  //     name: 'Portugal',
  //   },
  //   {
  //     code: 'PR',
  //     dial_code: '+1939',
  //     flag: require('../../assets/images/flags/pr.png'),
  //     name: 'Puerto Rico',
  //   },
  //   {
  //     code: 'QA',
  //     dial_code: '+974',
  //     flag: require('../../assets/images/flags/qa.png'),
  //     name: 'Qatar',
  //   },
  //   {
  //     code: 'RO',
  //     dial_code: '+40',
  //     flag: require('../../assets/images/flags/ro.png'),
  //     name: 'Romania',
  //   },
  //   {
  //     code: 'RU',
  //     dial_code: '+7',
  //     flag: require('../../assets/images/flags/ru.png'),
  //     name: 'Russia',
  //   },
  //   {
  //     code: 'RW',
  //     dial_code: '+250',
  //     flag: require('../../assets/images/flags/rw.png'),
  //     name: 'Rwanda',
  //   },
  //   {
  //     code: 'RE',
  //     dial_code: '+262',
  //     flag: require('../../assets/images/flags/re.png'),
  //     name: 'Reunion',
  //   },
  //   {
  //     code: 'BL',
  //     dial_code: '+590',
  //     flag: require('../../assets/images/flags/bl.png'),
  //     name: 'Saint Barthelemy',
  //   },
  //   {
  //     code: 'SH',
  //     dial_code: '+290',
  //     flag: require('../../assets/images/flags/sh.png'),
  //     name: 'Saint Helena, Ascension and Tristan Da Cunha',
  //   },
  //   {
  //     code: 'KN',
  //     dial_code: '+1869',
  //     flag: require('../../assets/images/flags/kn.png'),
  //     name: 'Saint Kitts and Nevis',
  //   },
  //   {
  //     code: 'LC',
  //     dial_code: '+1758',
  //     flag: require('../../assets/images/flags/lc.png'),
  //     name: 'Saint Lucia',
  //   },
  //   {
  //     code: 'MF',
  //     dial_code: '+590',
  //     flag: require('../../assets/images/flags/mf.png'),
  //     name: 'Saint Martin',
  //   },
  //   {
  //     code: 'PM',
  //     dial_code: '+508',
  //     flag: require('../../assets/images/flags/pm.png'),
  //     name: 'Saint Pierre and Miquelon',
  //   },
  //   {
  //     code: 'VC',
  //     dial_code: '+1784',
  //     flag: require('../../assets/images/flags/vc.png'),
  //     name: 'Saint Vincent and the Grenadines',
  //   },
  //   {
  //     code: 'WS',
  //     dial_code: '+685',
  //     flag: require('../../assets/images/flags/ws.png'),
  //     name: 'Samoa',
  //   },
  //   {
  //     code: 'SM',
  //     dial_code: '+378',
  //     flag: require('../../assets/images/flags/sm.png'),
  //     name: 'San Marino',
  //   },
  //   {
  //     code: 'ST',
  //     dial_code: '+239',
  //     flag: require('../../assets/images/flags/st.png'),
  //     name: 'Sao Tome and Principe',
  //   },
  //   {
  //     code: 'SA',
  //     dial_code: '+966',
  //     flag: require('../../assets/images/flags/sa.png'),
  //     name: 'Saudi Arabia',
  //   },
  //   {
  //     code: 'SN',
  //     dial_code: '+221',
  //     flag: require('../../assets/images/flags/sn.png'),
  //     name: 'Senegal',
  //   },
  //   {
  //     code: 'RS',
  //     dial_code: '+381',
  //     flag: require('../../assets/images/flags/rs.png'),
  //     name: 'Serbia',
  //   },
  //   {
  //     code: 'SC',
  //     dial_code: '+248',
  //     flag: require('../../assets/images/flags/sc.png'),
  //     name: 'Seychelles',
  //   },
  //   {
  //     code: 'SL',
  //     dial_code: '+232',
  //     flag: require('../../assets/images/flags/sl.png'),
  //     name: 'Sierra Leone',
  //   },
  //   {
  //     code: 'SG',
  //     dial_code: '+65',
  //     flag: require('../../assets/images/flags/sg.png'),
  //     name: 'Singapore',
  //   },
  //   {
  //     code: 'SK',
  //     dial_code: '+421',
  //     flag: require('../../assets/images/flags/sk.png'),
  //     name: 'Slovakia',
  //   },
  //   {
  //     code: 'SI',
  //     dial_code: '+386',
  //     flag: require('../../assets/images/flags/si.png'),
  //     name: 'Slovenia',
  //   },
  //   {
  //     code: 'SB',
  //     dial_code: '+677',
  //     flag: require('../../assets/images/flags/sb.png'),
  //     name: 'Solomon Islands',
  //   },
  //   {
  //     code: 'SO',
  //     dial_code: '+252',
  //     flag: require('../../assets/images/flags/so.png'),
  //     name: 'Somalia',
  //   },
  //   {
  //     code: 'ZA',
  //     dial_code: '+27',
  //     flag: require('../../assets/images/flags/za.png'),
  //     name: 'South Africa',
  //   },
  //   {
  //     code: 'SS',
  //     dial_code: '+211',
  //     flag: require('../../assets/images/flags/ss.png'),
  //     name: 'South Sudan',
  //   },
  //   {
  //     code: 'GS',
  //     dial_code: '+500',
  //     flag: require('../../assets/images/flags/gs.png'),
  //     name: 'South Georgia and the South Sandwich Islands',
  //   },
  //   {
  //     code: 'ES',
  //     dial_code: '+34',
  //     flag: require('../../assets/images/flags/es.png'),
  //     name: 'Spain',
  //   },
  //   {
  //     code: 'LK',
  //     dial_code: '+94',
  //     flag: require('../../assets/images/flags/lk.png'),
  //     name: 'Sri Lanka',
  //   },
  //   {
  //     code: 'SD',
  //     dial_code: '+249',
  //     flag: require('../../assets/images/flags/sd.png'),
  //     name: 'Sudan',
  //   },
  //   {
  //     code: 'SR',
  //     dial_code: '+597',
  //     flag: require('../../assets/images/flags/sr.png'),
  //     name: 'Suriname',
  //   },
  //   {
  //     code: 'SJ',
  //     dial_code: '+47',
  //     flag: require('../../assets/images/flags/sj.png'),
  //     name: 'Svalbard and Jan Mayen',
  //   },
  //   {
  //     code: 'SZ',
  //     dial_code: '+268',
  //     flag: require('../../assets/images/flags/sz.png'),
  //     name: 'Swaziland',
  //   },
  //   {
  //     code: 'SE',
  //     dial_code: '+46',
  //     flag: require('../../assets/images/flags/se.png'),
  //     name: 'Sweden',
  //   },
  //   {
  //     code: 'CH',
  //     dial_code: '+41',
  //     flag: require('../../assets/images/flags/ch.png'),
  //     name: 'Switzerland',
  //   },
  //   {
  //     code: 'SY',
  //     dial_code: '+963',
  //     flag: require('../../assets/images/flags/sy.png'),
  //     name: 'Syrian Arab Republic',
  //   },
  //   {
  //     code: 'TW',
  //     dial_code: '+886',
  //     flag: require('../../assets/images/flags/tw.png'),
  //     name: 'Taiwan',
  //   },
  //   {
  //     code: 'TJ',
  //     dial_code: '+992',
  //     flag: require('../../assets/images/flags/tj.png'),
  //     name: 'Tajikistan',
  //   },
  //   {
  //     code: 'TZ',
  //     dial_code: '+255',
  //     flag: require('../../assets/images/flags/tz.png'),
  //     name: 'Tanzania, United Republic of Tanzania',
  //   },
  //   {
  //     code: 'TH',
  //     dial_code: '+66',
  //     flag: require('../../assets/images/flags/th.png'),
  //     name: 'Thailand',
  //   },
  //   {
  //     code: 'TL',
  //     dial_code: '+670',
  //     flag: require('../../assets/images/flags/tl.png'),
  //     name: 'Timor-Leste',
  //   },
  //   {
  //     code: 'TG',
  //     dial_code: '+228',
  //     flag: require('../../assets/images/flags/tg.png'),
  //     name: 'Togo',
  //   },
  //   {
  //     code: 'TK',
  //     dial_code: '+690',
  //     flag: require('../../assets/images/flags/tk.png'),
  //     name: 'Tokelau',
  //   },
  //   {
  //     code: 'TO',
  //     dial_code: '+676',
  //     flag: require('../../assets/images/flags/to.png'),
  //     name: 'Tonga',
  //   },
  //   {
  //     code: 'TT',
  //     dial_code: '+1868',
  //     flag: require('../../assets/images/flags/tt.png'),
  //     name: 'Trinidad and Tobago',
  //   },
  //   {
  //     code: 'TN',
  //     dial_code: '+216',
  //     flag: require('../../assets/images/flags/tn.png'),
  //     name: 'Tunisia',
  //   },
  //   {
  //     code: 'TR',
  //     dial_code: '+90',
  //     flag: require('../../assets/images/flags/tr.png'),
  //     name: 'Turkey',
  //   },
  //   {
  //     code: 'TM',
  //     dial_code: '+993',
  //     flag: require('../../assets/images/flags/tm.png'),
  //     name: 'Turkmenistan',
  //   },
  //   {
  //     code: 'TC',
  //     dial_code: '+1649',
  //     flag: require('../../assets/images/flags/tc.png'),
  //     name: 'Turks and Caicos Islands',
  //   },
  //   {
  //     code: 'TV',
  //     dial_code: '+688',
  //     flag: require('../../assets/images/flags/tv.png'),
  //     name: 'Tuvalu',
  //   },
  //   {
  //     code: 'UG',
  //     dial_code: '+256',
  //     flag: require('../../assets/images/flags/ug.png'),
  //     name: 'Uganda',
  //   },
  //   {
  //     code: 'UA',
  //     dial_code: '+380',
  //     flag: require('../../assets/images/flags/ua.png'),
  //     name: 'Ukraine',
  //   },
  //   {
  //     code: 'AE',
  //     dial_code: '+971',
  //     flag: require('../../assets/images/flags/ae.png'),
  //     name: 'United Arab Emirates',
  //   },
  //   {
  //     code: 'GB',
  //     dial_code: '+44',
  //     flag: require('../../assets/images/flags/gb.png'),
  //     name: 'United Kingdom',
  //   },
  //   {
  //     code: 'US',
  //     dial_code: '+1',
  //     flag: require('../../assets/images/flags/us.png'),
  //     name: 'United States',
  //   },
  //   {
  //     code: 'UY',
  //     dial_code: '+598',
  //     flag: require('../../assets/images/flags/uy.png'),
  //     name: 'Uruguay',
  //   },
  //   {
  //     code: 'UZ',
  //     dial_code: '+998',
  //     flag: require('../../assets/images/flags/uz.png'),
  //     name: 'Uzbekistan',
  //   },
  //   {
  //     code: 'VU',
  //     dial_code: '+678',
  //     flag: require('../../assets/images/flags/vu.png'),
  //     name: 'Vanuatu',
  //   },
  //   {
  //     code: 'VE',
  //     dial_code: '+58',
  //     flag: require('../../assets/images/flags/ve.png'),
  //     name: 'Venezuela, Bolivarian Republic of Venezuela',
  //   },
  //   {
  //     code: 'VN',
  //     dial_code: '+84',
  //     flag: require('../../assets/images/flags/vn.png'),
  //     name: 'Vietnam',
  //   },
  //   {
  //     code: 'VG',
  //     dial_code: '+1284',
  //     flag: require('../../assets/images/flags/vg.png'),
  //     name: 'Virgin Islands, British',
  //   },
  //   {
  //     code: 'VI',
  //     dial_code: '+1340',
  //     flag: require('../../assets/images/flags/vi.png'),
  //     name: 'Virgin Islands, U.S.',
  //   },
  //   {
  //     code: 'WF',
  //     dial_code: '+681',
  //     flag: require('../../assets/images/flags/wf.png'),
  //     name: 'Wallis and Futuna',
  //   },
  //   {
  //     code: 'YE',
  //     dial_code: '+967',
  //     flag: require('../../assets/images/flags/ye.png'),
  //     name: 'Yemen',
  //   },
  //   {
  //     code: 'ZM',
  //     dial_code: '+260',
  //     flag: require('../../assets/images/flags/zm.png'),
  //     name: 'Zambia',
  //   },
  //   {
  //     code: 'ZW',
  //     dial_code: '+263',
  //     flag: require('../../assets/images/flags/zw.png'),
  //     name: 'Zimbabwe',
  //   },
  // ],
  countryCodes: [
    // {
    //   name: 'Iraq',
    //   dial_code: '+964',
    //   code: 'IQ',
    // },
    // {
    //   name: 'Afghanistan',
    //   dial_code: '+93',
    //   code: 'AF',
    // },
    // {
    //   name: 'Aland Islands',
    //   dial_code: '+358',
    //   code: 'AX',
    // },
    // {
    //   name: 'Albania',
    //   dial_code: '+355',
    //   code: 'AL',
    // },
    // {
    //   name: 'Algeria',
    //   dial_code: '+213',
    //   code: 'DZ',
    // },
    // {
    //   name: 'AmericanSamoa',
    //   dial_code: '+1684',
    //   code: 'AS',
    // },
    // {
    //   name: 'Andorra',
    //   dial_code: '+376',
    //   code: 'AD',
    // },
    // {
    //   name: 'Angola',
    //   dial_code: '+244',
    //   code: 'AO',
    // },
    // {
    //   name: 'Anguilla',
    //   dial_code: '+1264',
    //   code: 'AI',
    // },
    // {
    //   name: 'Antarctica',
    //   dial_code: '+672',
    //   code: 'AQ',
    // },
    // {
    //   name: 'Antigua and Barbuda',
    //   dial_code: '+1268',
    //   code: 'AG',
    // },
    // {
    //   name: 'Argentina',
    //   dial_code: '+54',
    //   code: 'AR',
    // },
    // {
    //   name: 'Armenia',
    //   dial_code: '+374',
    //   code: 'AM',
    // },
    // {
    //   name: 'Aruba',
    //   dial_code: '+297',
    //   code: 'AW',
    // },
    // {
    //   name: 'Australia',
    //   dial_code: '+61',
    //   code: 'AU',
    // },
    // {
    //   name: 'Austria',
    //   dial_code: '+43',
    //   code: 'AT',
    // },
    // {
    //   name: 'Azerbaijan',
    //   dial_code: '+994',
    //   code: 'AZ',
    // },
    // {
    //   name: 'Bahamas',
    //   dial_code: '+1242',
    //   code: 'BS',
    // },
    // {
    //   name: 'Bahrain',
    //   dial_code: '+973',
    //   code: 'BH',
    // },
    // {
    //   name: 'Bangladesh',
    //   dial_code: '+880',
    //   code: 'BD',
    // },
    // {
    //   name: 'Barbados',
    //   dial_code: '+1246',
    //   code: 'BB',
    // },
    // {
    //   name: 'Belarus',
    //   dial_code: '+375',
    //   code: 'BY',
    // },
    // {
    //   name: 'Belgium',
    //   dial_code: '+32',
    //   code: 'BE',
    // },
    // {
    //   name: 'Belize',
    //   dial_code: '+501',
    //   code: 'BZ',
    // },
    // {
    //   name: 'Benin',
    //   dial_code: '+229',
    //   code: 'BJ',
    // },
    // {
    //   name: 'Bermuda',
    //   dial_code: '+1441',
    //   code: 'BM',
    // },
    // {
    //   name: 'Bhutan',
    //   dial_code: '+975',
    //   code: 'BT',
    // },
    // {
    //   name: 'Bolivia, Plurinational State of',
    //   dial_code: '+591',
    //   code: 'BO',
    // },
    // {
    //   name: 'Bosnia and Herzegovina',
    //   dial_code: '+387',
    //   code: 'BA',
    // },
    // {
    //   name: 'Botswana',
    //   dial_code: '+267',
    //   code: 'BW',
    // },
    // {
    //   name: 'Brazil',
    //   dial_code: '+55',
    //   code: 'BR',
    // },
    // {
    //   name: 'British Indian Ocean Territory',
    //   dial_code: '+246',
    //   code: 'IO',
    // },
    // {
    //   name: 'Brunei Darussalam',
    //   dial_code: '+673',
    //   code: 'BN',
    // },
    // {
    //   name: 'Bulgaria',
    //   dial_code: '+359',
    //   code: 'BG',
    // },
    // {
    //   name: 'Burkina Faso',
    //   dial_code: '+226',
    //   code: 'BF',
    // },
    // {
    //   name: 'Burundi',
    //   dial_code: '+257',
    //   code: 'BI',
    // },
    // {
    //   name: 'Cambodia',
    //   dial_code: '+855',
    //   code: 'KH',
    // },
    // {
    //   name: 'Cameroon',
    //   dial_code: '+237',
    //   code: 'CM',
    // },
    {
      name: 'Canada',
      dial_code: '+1',
      code: 'CA',
    },
    // {
    //   name: 'Cape Verde',
    //   dial_code: '+238',
    //   code: 'CV',
    // },
    // {
    //   name: 'Cayman Islands',
    //   dial_code: '+ 345',
    //   code: 'KY',
    // },
    // {
    //   name: 'Central African Republic',
    //   dial_code: '+236',
    //   code: 'CF',
    // },
    // {
    //   name: 'Chad',
    //   dial_code: '+235',
    //   code: 'TD',
    // },
    // {
    //   name: 'Chile',
    //   dial_code: '+56',
    //   code: 'CL',
    // },
    // {
    //   name: 'China',
    //   dial_code: '+86',
    //   code: 'CN',
    // },
    // {
    //   name: 'Christmas Island',
    //   dial_code: '+61',
    //   code: 'CX',
    // },
    // {
    //   name: 'Cocos (Keeling) Islands',
    //   dial_code: '+61',
    //   code: 'CC',
    // },
    // {
    //   name: 'Colombia',
    //   dial_code: '+57',
    //   code: 'CO',
    // },
    // {
    //   name: 'Comoros',
    //   dial_code: '+269',
    //   code: 'KM',
    // },
    // {
    //   name: 'Congo',
    //   dial_code: '+242',
    //   code: 'CG',
    // },
    // {
    //   name: 'Congo, The Democratic Republic of the Congo',
    //   dial_code: '+243',
    //   code: 'CD',
    // },
    // {
    //   name: 'Cook Islands',
    //   dial_code: '+682',
    //   code: 'CK',
    // },
    // {
    //   name: 'Costa Rica',
    //   dial_code: '+506',
    //   code: 'CR',
    // },
    // {
    //   name: "Cote d'Ivoire",
    //   dial_code: '+225',
    //   code: 'CI',
    // },
    // {
    //   name: 'Croatia',
    //   dial_code: '+385',
    //   code: 'HR',
    // },
    // {
    //   name: 'Cuba',
    //   dial_code: '+53',
    //   code: 'CU',
    // },
    // {
    //   name: 'Cyprus',
    //   dial_code: '+357',
    //   code: 'CY',
    // },
    // {
    //   name: 'Czech Republic',
    //   dial_code: '+420',
    //   code: 'CZ',
    // },
    // {
    //   name: 'Denmark',
    //   dial_code: '+45',
    //   code: 'DK',
    // },
    // {
    //   name: 'Djibouti',
    //   dial_code: '+253',
    //   code: 'DJ',
    // },
    // {
    //   name: 'Dominica',
    //   dial_code: '+1767',
    //   code: 'DM',
    // },
    // {
    //   name: 'Dominican Republic',
    //   dial_code: '+1849',
    //   code: 'DO',
    // },
    // {
    //   name: 'Ecuador',
    //   dial_code: '+593',
    //   code: 'EC',
    // },
    // {
    //   name: 'Egypt',
    //   dial_code: '+20',
    //   code: 'EG',
    // },
    // {
    //   name: 'El Salvador',
    //   dial_code: '+503',
    //   code: 'SV',
    // },
    // {
    //   name: 'Equatorial Guinea',
    //   dial_code: '+240',
    //   code: 'GQ',
    // },
    // {
    //   name: 'Eritrea',
    //   dial_code: '+291',
    //   code: 'ER',
    // },
    // {
    //   name: 'Estonia',
    //   dial_code: '+372',
    //   code: 'EE',
    // },
    // {
    //   name: 'Ethiopia',
    //   dial_code: '+251',
    //   code: 'ET',
    // },
    // {
    //   name: 'Falkland Islands (Malvinas)',
    //   dial_code: '+500',
    //   code: 'FK',
    // },
    // {
    //   name: 'Faroe Islands',
    //   dial_code: '+298',
    //   code: 'FO',
    // },
    // {
    //   name: 'Fiji',
    //   dial_code: '+679',
    //   code: 'FJ',
    // },
    // {
    //   name: 'Finland',
    //   dial_code: '+358',
    //   code: 'FI',
    // },
    // {
    //   name: 'France',
    //   dial_code: '+33',
    //   code: 'FR',
    // },
    // {
    //   name: 'French Guiana',
    //   dial_code: '+594',
    //   code: 'GF',
    // },
    // {
    //   name: 'French Polynesia',
    //   dial_code: '+689',
    //   code: 'PF',
    // },
    // {
    //   name: 'Gabon',
    //   dial_code: '+241',
    //   code: 'GA',
    // },
    // {
    //   name: 'Gambia',
    //   dial_code: '+220',
    //   code: 'GM',
    // },
    // {
    //   name: 'Georgia',
    //   dial_code: '+995',
    //   code: 'GE',
    // },
    // {
    //   name: 'Germany',
    //   dial_code: '+49',
    //   code: 'DE',
    // },
    // {
    //   name: 'Ghana',
    //   dial_code: '+233',
    //   code: 'GH',
    // },
    // {
    //   name: 'Gibraltar',
    //   dial_code: '+350',
    //   code: 'GI',
    // },
    // {
    //   name: 'Greece',
    //   dial_code: '+30',
    //   code: 'GR',
    // },
    // {
    //   name: 'Greenland',
    //   dial_code: '+299',
    //   code: 'GL',
    // },
    // {
    //   name: 'Grenada',
    //   dial_code: '+1473',
    //   code: 'GD',
    // },
    // {
    //   name: 'Guadeloupe',
    //   dial_code: '+590',
    //   code: 'GP',
    // },
    // {
    //   name: 'Guam',
    //   dial_code: '+1671',
    //   code: 'GU',
    // },
    // {
    //   name: 'Guatemala',
    //   dial_code: '+502',
    //   code: 'GT',
    // },
    // {
    //   name: 'Guernsey',
    //   dial_code: '+44',
    //   code: 'GG',
    // },
    // {
    //   name: 'Guinea',
    //   dial_code: '+224',
    //   code: 'GN',
    // },
    // {
    //   name: 'Guinea-Bissau',
    //   dial_code: '+245',
    //   code: 'GW',
    // },
    // {
    //   name: 'Guyana',
    //   dial_code: '+595',
    //   code: 'GY',
    // },
    // {
    //   name: 'Haiti',
    //   dial_code: '+509',
    //   code: 'HT',
    // },
    // {
    //   name: 'Holy See (Vatican City State)',
    //   dial_code: '+379',
    //   code: 'VA',
    // },
    // {
    //   name: 'Honduras',
    //   dial_code: '+504',
    //   code: 'HN',
    // },
    // {
    //   name: 'Hong Kong',
    //   dial_code: '+852',
    //   code: 'HK',
    // },
    // {
    //   name: 'Hungary',
    //   dial_code: '+36',
    //   code: 'HU',
    // },
    // {
    //   name: 'Iceland',
    //   dial_code: '+354',
    //   code: 'IS',
    // },
    {
      name: 'India',
      dial_code: '+91',
      code: 'IN',
    },
    // {
    //   name: 'Indonesia',
    //   dial_code: '+62',
    //   code: 'ID',
    // },
    // {
    //   name: 'Iran, Islamic Republic of Persian Gulf',
    //   dial_code: '+98',
    //   code: 'IR',
    // },
    // {
    //   name: 'Ireland',
    //   dial_code: '+353',
    //   code: 'IE',
    // },
    // {
    //   name: 'Isle of Man',
    //   dial_code: '+44',
    //   code: 'IM',
    // },
    // {
    //   name: 'Israel',
    //   dial_code: '+972',
    //   code: 'IL',
    // },
    // {
    //   name: 'Italy',
    //   dial_code: '+39',
    //   code: 'IT',
    // },
    // {
    //   name: 'Jamaica',
    //   dial_code: '+1876',
    //   code: 'JM',
    // },
    // {
    //   name: 'Japan',
    //   dial_code: '+81',
    //   code: 'JP',
    // },
    // {
    //   name: 'Jersey',
    //   dial_code: '+44',
    //   code: 'JE',
    // },
    // {
    //   name: 'Jordan',
    //   dial_code: '+962',
    //   code: 'JO',
    // },
    // {
    //   name: 'Kazakhstan',
    //   dial_code: '+77',
    //   code: 'KZ',
    // },
    // {
    //   name: 'Kenya',
    //   dial_code: '+254',
    //   code: 'KE',
    // },
    // {
    //   name: 'Kiribati',
    //   dial_code: '+686',
    //   code: 'KI',
    // },
    // {
    //   name: "Korea, Democratic People's Republic of Korea",
    //   dial_code: '+850',
    //   code: 'KP',
    // },
    // {
    //   name: 'Korea, Republic of South Korea',
    //   dial_code: '+82',
    //   code: 'KR',
    // },
    // {
    //   name: 'Kuwait',
    //   dial_code: '+965',
    //   code: 'KW',
    // },
    // {
    //   name: 'Kyrgyzstan',
    //   dial_code: '+996',
    //   code: 'KG',
    // },
    // {
    //   name: 'Laos',
    //   dial_code: '+856',
    //   code: 'LA',
    // },
    // {
    //   name: 'Latvia',
    //   dial_code: '+371',
    //   code: 'LV',
    // },
    // {
    //   name: 'Lebanon',
    //   dial_code: '+961',
    //   code: 'LB',
    // },
    // {
    //   name: 'Lesotho',
    //   dial_code: '+266',
    //   code: 'LS',
    // },
    // {
    //   name: 'Liberia',
    //   dial_code: '+231',
    //   code: 'LR',
    // },
    // {
    //   name: 'Libyan Arab Jamahiriya',
    //   dial_code: '+218',
    //   code: 'LY',
    // },
    // {
    //   name: 'Liechtenstein',
    //   dial_code: '+423',
    //   code: 'LI',
    // },
    // {
    //   name: 'Lithuania',
    //   dial_code: '+370',
    //   code: 'LT',
    // },
    // {
    //   name: 'Luxembourg',
    //   dial_code: '+352',
    //   code: 'LU',
    // },
    // {
    //   name: 'Macao',
    //   dial_code: '+853',
    //   code: 'MO',
    // },
    // {
    //   name: 'Macedonia',
    //   dial_code: '+389',
    //   code: 'MK',
    // },
    // {
    //   name: 'Madagascar',
    //   dial_code: '+261',
    //   code: 'MG',
    // },
    // {
    //   name: 'Malawi',
    //   dial_code: '+265',
    //   code: 'MW',
    // },
    // {
    //   name: 'Malaysia',
    //   dial_code: '+60',
    //   code: 'MY',
    // },
    // {
    //   name: 'Maldives',
    //   dial_code: '+960',
    //   code: 'MV',
    // },
    // {
    //   name: 'Mali',
    //   dial_code: '+223',
    //   code: 'ML',
    // },
    // {
    //   name: 'Malta',
    //   dial_code: '+356',
    //   code: 'MT',
    // },
    // {
    //   name: 'Marshall Islands',
    //   dial_code: '+692',
    //   code: 'MH',
    // },
    // {
    //   name: 'Martinique',
    //   dial_code: '+596',
    //   code: 'MQ',
    // },
    // {
    //   name: 'Mauritania',
    //   dial_code: '+222',
    //   code: 'MR',
    // },
    // {
    //   name: 'Mauritius',
    //   dial_code: '+230',
    //   code: 'MU',
    // },
    // {
    //   name: 'Mayotte',
    //   dial_code: '+262',
    //   code: 'YT',
    // },
    // {
    //   name: 'Mexico',
    //   dial_code: '+52',
    //   code: 'MX',
    // },
    // {
    //   name: 'Micronesia, Federated States of Micronesia',
    //   dial_code: '+691',
    //   code: 'FM',
    // },
    // {
    //   name: 'Moldova',
    //   dial_code: '+373',
    //   code: 'MD',
    // },
    // {
    //   name: 'Monaco',
    //   dial_code: '+377',
    //   code: 'MC',
    // },
    // {
    //   name: 'Mongolia',
    //   dial_code: '+976',
    //   code: 'MN',
    // },
    // {
    //   name: 'Montenegro',
    //   dial_code: '+382',
    //   code: 'ME',
    // },
    // {
    //   name: 'Montserrat',
    //   dial_code: '+1664',
    //   code: 'MS',
    // },
    // {
    //   name: 'Morocco',
    //   dial_code: '+212',
    //   code: 'MA',
    // },
    // {
    //   name: 'Mozambique',
    //   dial_code: '+258',
    //   code: 'MZ',
    // },
    // {
    //   name: 'Myanmar',
    //   dial_code: '+95',
    //   code: 'MM',
    // },
    // {
    //   name: 'Namibia',
    //   dial_code: '+264',
    //   code: 'NA',
    // },
    // {
    //   name: 'Nauru',
    //   dial_code: '+674',
    //   code: 'NR',
    // },
    // {
    //   name: 'Nepal',
    //   dial_code: '+977',
    //   code: 'NP',
    // },
    // {
    //   name: 'Netherlands',
    //   dial_code: '+31',
    //   code: 'NL',
    // },
    // {
    //   name: 'Netherlands Antilles',
    //   dial_code: '+599',
    //   code: 'AN',
    // },
    // {
    //   name: 'New Caledonia',
    //   dial_code: '+687',
    //   code: 'NC',
    // },
    // {
    //   name: 'New Zealand',
    //   dial_code: '+64',
    //   code: 'NZ',
    // },
    // {
    //   name: 'Nicaragua',
    //   dial_code: '+505',
    //   code: 'NI',
    // },
    // {
    //   name: 'Niger',
    //   dial_code: '+227',
    //   code: 'NE',
    // },
    // {
    //   name: 'Nigeria',
    //   dial_code: '+234',
    //   code: 'NG',
    // },
    // {
    //   name: 'Niue',
    //   dial_code: '+683',
    //   code: 'NU',
    // },
    // {
    //   name: 'Norfolk Island',
    //   dial_code: '+672',
    //   code: 'NF',
    // },
    // {
    //   name: 'Northern Mariana Islands',
    //   dial_code: '+1670',
    //   code: 'MP',
    // },
    // {
    //   name: 'Norway',
    //   dial_code: '+47',
    //   code: 'NO',
    // },
    // {
    //   name: 'Oman',
    //   dial_code: '+968',
    //   code: 'OM',
    // },
    // {
    //   name: 'Pakistan',
    //   dial_code: '+92',
    //   code: 'PK',
    // },
    // {
    //   name: 'Palau',
    //   dial_code: '+680',
    //   code: 'PW',
    // },
    // {
    //   name: 'Palestinian Territory, Occupied',
    //   dial_code: '+970',
    //   code: 'PS',
    // },
    // {
    //   name: 'Panama',
    //   dial_code: '+507',
    //   code: 'PA',
    // },
    // {
    //   name: 'Papua New Guinea',
    //   dial_code: '+675',
    //   code: 'PG',
    // },
    // {
    //   name: 'Paraguay',
    //   dial_code: '+595',
    //   code: 'PY',
    // },
    // {
    //   name: 'Peru',
    //   dial_code: '+51',
    //   code: 'PE',
    // },
    // {
    //   name: 'Philippines',
    //   dial_code: '+63',
    //   code: 'PH',
    // },
    // {
    //   name: 'Pitcairn',
    //   dial_code: '+872',
    //   code: 'PN',
    // },
    // {
    //   name: 'Poland',
    //   dial_code: '+48',
    //   code: 'PL',
    // },
    // {
    //   name: 'Portugal',
    //   dial_code: '+351',
    //   code: 'PT',
    // },
    // {
    //   name: 'Puerto Rico',
    //   dial_code: '+1939',
    //   code: 'PR',
    // },
    // {
    //   name: 'Qatar',
    //   dial_code: '+974',
    //   code: 'QA',
    // },
    // {
    //   name: 'Romania',
    //   dial_code: '+40',
    //   code: 'RO',
    // },
    // {
    //   name: 'Russia',
    //   dial_code: '+7',
    //   code: 'RU',
    // },
    // {
    //   name: 'Rwanda',
    //   dial_code: '+250',
    //   code: 'RW',
    // },
    // {
    //   name: 'Reunion',
    //   dial_code: '+262',
    //   code: 'RE',
    // },
    // {
    //   name: 'Saint Barthelemy',
    //   dial_code: '+590',
    //   code: 'BL',
    // },
    // {
    //   name: 'Saint Helena, Ascension and Tristan Da Cunha',
    //   dial_code: '+290',
    //   code: 'SH',
    // },
    // {
    //   name: 'Saint Kitts and Nevis',
    //   dial_code: '+1869',
    //   code: 'KN',
    // },
    // {
    //   name: 'Saint Lucia',
    //   dial_code: '+1758',
    //   code: 'LC',
    // },
    // {
    //   name: 'Saint Martin',
    //   dial_code: '+590',
    //   code: 'MF',
    // },
    // {
    //   name: 'Saint Pierre and Miquelon',
    //   dial_code: '+508',
    //   code: 'PM',
    // },
    // {
    //   name: 'Saint Vincent and the Grenadines',
    //   dial_code: '+1784',
    //   code: 'VC',
    // },
    // {
    //   name: 'Samoa',
    //   dial_code: '+685',
    //   code: 'WS',
    // },
    // {
    //   name: 'San Marino',
    //   dial_code: '+378',
    //   code: 'SM',
    // },
    // {
    //   name: 'Sao Tome and Principe',
    //   dial_code: '+239',
    //   code: 'ST',
    // },
    // {
    //   name: 'Saudi Arabia',
    //   dial_code: '+966',
    //   code: 'SA',
    // },
    // {
    //   name: 'Senegal',
    //   dial_code: '+221',
    //   code: 'SN',
    // },
    // {
    //   name: 'Serbia',
    //   dial_code: '+381',
    //   code: 'RS',
    // },
    // {
    //   name: 'Seychelles',
    //   dial_code: '+248',
    //   code: 'SC',
    // },
    // {
    //   name: 'Sierra Leone',
    //   dial_code: '+232',
    //   code: 'SL',
    // },
    // {
    //   name: 'Singapore',
    //   dial_code: '+65',
    //   code: 'SG',
    // },
    // {
    //   name: 'Slovakia',
    //   dial_code: '+421',
    //   code: 'SK',
    // },
    // {
    //   name: 'Slovenia',
    //   dial_code: '+386',
    //   code: 'SI',
    // },
    // {
    //   name: 'Solomon Islands',
    //   dial_code: '+677',
    //   code: 'SB',
    // },
    // {
    //   name: 'Somalia',
    //   dial_code: '+252',
    //   code: 'SO',
    // },
    // {
    //   name: 'South Africa',
    //   dial_code: '+27',
    //   code: 'ZA',
    // },
    // {
    //   name: 'South Sudan',
    //   dial_code: '+211',
    //   code: 'SS',
    // },
    // {
    //   name: 'South Georgia and the South Sandwich Islands',
    //   dial_code: '+500',
    //   code: 'GS',
    // },
    // {
    //   name: 'Spain',
    //   dial_code: '+34',
    //   code: 'ES',
    // },
    // {
    //   name: 'Sri Lanka',
    //   dial_code: '+94',
    //   code: 'LK',
    // },
    // {
    //   name: 'Sudan',
    //   dial_code: '+249',
    //   code: 'SD',
    // },
    // {
    //   name: 'Suriname',
    //   dial_code: '+597',
    //   code: 'SR',
    // },
    // {
    //   name: 'Svalbard and Jan Mayen',
    //   dial_code: '+47',
    //   code: 'SJ',
    // },
    // {
    //   name: 'Swaziland',
    //   dial_code: '+268',
    //   code: 'SZ',
    // },
    // {
    //   name: 'Sweden',
    //   dial_code: '+46',
    //   code: 'SE',
    // },
    // {
    //   name: 'Switzerland',
    //   dial_code: '+41',
    //   code: 'CH',
    // },
    // {
    //   name: 'Syrian Arab Republic',
    //   dial_code: '+963',
    //   code: 'SY',
    // },
    // {
    //   name: 'Taiwan',
    //   dial_code: '+886',
    //   code: 'TW',
    // },
    // {
    //   name: 'Tajikistan',
    //   dial_code: '+992',
    //   code: 'TJ',
    // },
    // {
    //   name: 'Tanzania, United Republic of Tanzania',
    //   dial_code: '+255',
    //   code: 'TZ',
    // },
    // {
    //   name: 'Thailand',
    //   dial_code: '+66',
    //   code: 'TH',
    // },
    // {
    //   name: 'Timor-Leste',
    //   dial_code: '+670',
    //   code: 'TL',
    // },
    // {
    //   name: 'Togo',
    //   dial_code: '+228',
    //   code: 'TG',
    // },
    // {
    //   name: 'Tokelau',
    //   dial_code: '+690',
    //   code: 'TK',
    // },
    // {
    //   name: 'Tonga',
    //   dial_code: '+676',
    //   code: 'TO',
    // },
    // {
    //   name: 'Trinidad and Tobago',
    //   dial_code: '+1868',
    //   code: 'TT',
    // },
    // {
    //   name: 'Tunisia',
    //   dial_code: '+216',
    //   code: 'TN',
    // },
    // {
    //   name: 'Turkey',
    //   dial_code: '+90',
    //   code: 'TR',
    // },
    // {
    //   name: 'Turkmenistan',
    //   dial_code: '+993',
    //   code: 'TM',
    // },
    // {
    //   name: 'Turks and Caicos Islands',
    //   dial_code: '+1649',
    //   code: 'TC',
    // },
    // {
    //   name: 'Tuvalu',
    //   dial_code: '+688',
    //   code: 'TV',
    // },
    // {
    //   name: 'Uganda',
    //   dial_code: '+256',
    //   code: 'UG',
    // },
    // {
    //   name: 'Ukraine',
    //   dial_code: '+380',
    //   code: 'UA',
    // },
    // {
    //   name: 'United Arab Emirates',
    //   dial_code: '+971',
    //   code: 'AE',
    // },
    // {
    //   name: 'United Kingdom',
    //   dial_code: '+44',
    //   code: 'GB',
    // },
    // {
    //   name: 'United States',
    //   dial_code: '+1',
    //   code: 'US',
    // },
    // {
    //   name: 'Uruguay',
    //   dial_code: '+598',
    //   code: 'UY',
    // },
    // {
    //   name: 'Uzbekistan',
    //   dial_code: '+998',
    //   code: 'UZ',
    // },
    // {
    //   name: 'Vanuatu',
    //   dial_code: '+678',
    //   code: 'VU',
    // },
    // {
    //   name: 'Venezuela, Bolivarian Republic of Venezuela',
    //   dial_code: '+58',
    //   code: 'VE',
    // },
    // {
    //   name: 'Vietnam',
    //   dial_code: '+84',
    //   code: 'VN',
    // },
    // {
    //   name: 'Virgin Islands, British',
    //   dial_code: '+1284',
    //   code: 'VG',
    // },
    // {
    //   name: 'Virgin Islands, U.S.',
    //   dial_code: '+1340',
    //   code: 'VI',
    // },
    // {
    //   name: 'Wallis and Futuna',
    //   dial_code: '+681',
    //   code: 'WF',
    // },
    // {
    //   name: 'Yemen',
    //   dial_code: '+967',
    //   code: 'YE',
    // },
    // {
    //   name: 'Zambia',
    //   dial_code: '+260',
    //   code: 'ZM',
    // },
    // {
    //   name: 'Zimbabwe',
    //   dial_code: '+263',
    //   code: 'ZW',
    // },
  ],
};
